create index IX_FAF6CDC1 on webcmscustom.HAYSSALGUSERDATAUK (SGFROMLOCALE[$COLUMN_LENGTH:75$]);

create index IX_31127BE2 on webcmscustom.HAYSSGUSERDATA (FROMLOCALE[$COLUMN_LENGTH:75$]);

create index IX_68ED6563 on webcmscustom.HAYS_SALARY_GUIDE (INDUSTRY[$COLUMN_LENGTH:75$]);
create index IX_4D707E66 on webcmscustom.HAYS_SALARY_GUIDE (SITELOCALE[$COLUMN_LENGTH:75$]);