create table webcmscustom.HAYSSALGUSERDATAUK (
	SGUSERID LONG not null primary key,
	SGFORMINDUSTRY VARCHAR(75) null,
	SGFORMSECTOR VARCHAR(75) null,
	SGFORMAREA VARCHAR(75) null,
	SGFORMPOSITIONTYPE VARCHAR(75) null,
	SGFORMPOSITIONNAME VARCHAR(75) null,
	LOCATIONNAME VARCHAR(75) null,
	SGCOMPANY VARCHAR(75) null,
	SGCURRENTSALARY LONG,
	SGEMAIL VARCHAR(75) null,
	CREATETIMESTAMP DATE null,
	SGFROMLOCALE VARCHAR(75) null
);

create table webcmscustom.HAYSSGUSERDATA (
	SGUSERID LONG not null primary key,
	SGUSERNAME VARCHAR(75) null,
	SGJOBTITLE VARCHAR(75) null,
	SGORGANIZATION VARCHAR(75) null,
	SGLOCATION VARCHAR(75) null,
	SGEMAILADDRESS VARCHAR(75) null,
	FROMLOCALE VARCHAR(75) null,
	CREATETIMESTAMP DATE null
);

create table webcmscustom.HAYS_SALARY_GUIDE (
	INDUSTRY VARCHAR(75) null,
	LOCATIONNAME VARCHAR(75) null,
	SECTOR VARCHAR(75) null,
	POSITIONTYPE VARCHAR(75) null,
	AREA VARCHAR(75) null,
	COMPANY VARCHAR(75) null,
	POSITIONNAME VARCHAR(75) null,
	SALARYRANGE VARCHAR(75) null,
	SALARYTYPICAL VARCHAR(75) null,
	NOTE VARCHAR(75) null,
	SITELOCALE VARCHAR(75) null,
	SGDDOCNAME VARCHAR(75) null,
	SGID VARCHAR(75) not null primary key,
	SALARYTYPE VARCHAR(75) null
);