/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hays.service.salaryguide.service.base;

import aQute.bnd.annotation.ProviderType;

import com.hays.service.salaryguide.model.HaysSalGuideUserDataUk;
import com.hays.service.salaryguide.service.HaysSalGuideUserDataUkLocalService;
import com.hays.service.salaryguide.service.persistence.HaysSGUserDataPersistence;
import com.hays.service.salaryguide.service.persistence.HaysSalGuideUserDataUkPersistence;
import com.hays.service.salaryguide.service.persistence.HaysSalaryGuideFinder;
import com.hays.service.salaryguide.service.persistence.HaysSalaryGuidePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the hays sal guide user data uk local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.hays.service.salaryguide.service.impl.HaysSalGuideUserDataUkLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.hays.service.salaryguide.service.impl.HaysSalGuideUserDataUkLocalServiceImpl
 * @see com.hays.service.salaryguide.service.HaysSalGuideUserDataUkLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class HaysSalGuideUserDataUkLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements HaysSalGuideUserDataUkLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.hays.service.salaryguide.service.HaysSalGuideUserDataUkLocalServiceUtil} to access the hays sal guide user data uk local service.
	 */

	/**
	 * Adds the hays sal guide user data uk to the database. Also notifies the appropriate model listeners.
	 *
	 * @param haysSalGuideUserDataUk the hays sal guide user data uk
	 * @return the hays sal guide user data uk that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public HaysSalGuideUserDataUk addHaysSalGuideUserDataUk(
		HaysSalGuideUserDataUk haysSalGuideUserDataUk) {
		haysSalGuideUserDataUk.setNew(true);

		return haysSalGuideUserDataUkPersistence.update(haysSalGuideUserDataUk);
	}

	/**
	 * Creates a new hays sal guide user data uk with the primary key. Does not add the hays sal guide user data uk to the database.
	 *
	 * @param SGUSERID the primary key for the new hays sal guide user data uk
	 * @return the new hays sal guide user data uk
	 */
	@Override
	public HaysSalGuideUserDataUk createHaysSalGuideUserDataUk(long SGUSERID) {
		return haysSalGuideUserDataUkPersistence.create(SGUSERID);
	}

	/**
	 * Deletes the hays sal guide user data uk with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param SGUSERID the primary key of the hays sal guide user data uk
	 * @return the hays sal guide user data uk that was removed
	 * @throws PortalException if a hays sal guide user data uk with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public HaysSalGuideUserDataUk deleteHaysSalGuideUserDataUk(long SGUSERID)
		throws PortalException {
		return haysSalGuideUserDataUkPersistence.remove(SGUSERID);
	}

	/**
	 * Deletes the hays sal guide user data uk from the database. Also notifies the appropriate model listeners.
	 *
	 * @param haysSalGuideUserDataUk the hays sal guide user data uk
	 * @return the hays sal guide user data uk that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public HaysSalGuideUserDataUk deleteHaysSalGuideUserDataUk(
		HaysSalGuideUserDataUk haysSalGuideUserDataUk) {
		return haysSalGuideUserDataUkPersistence.remove(haysSalGuideUserDataUk);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(HaysSalGuideUserDataUk.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return haysSalGuideUserDataUkPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.hays.service.salaryguide.model.impl.HaysSalGuideUserDataUkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return haysSalGuideUserDataUkPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.hays.service.salaryguide.model.impl.HaysSalGuideUserDataUkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return haysSalGuideUserDataUkPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return haysSalGuideUserDataUkPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return haysSalGuideUserDataUkPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public HaysSalGuideUserDataUk fetchHaysSalGuideUserDataUk(long SGUSERID) {
		return haysSalGuideUserDataUkPersistence.fetchByPrimaryKey(SGUSERID);
	}

	/**
	 * Returns the hays sal guide user data uk with the primary key.
	 *
	 * @param SGUSERID the primary key of the hays sal guide user data uk
	 * @return the hays sal guide user data uk
	 * @throws PortalException if a hays sal guide user data uk with the primary key could not be found
	 */
	@Override
	public HaysSalGuideUserDataUk getHaysSalGuideUserDataUk(long SGUSERID)
		throws PortalException {
		return haysSalGuideUserDataUkPersistence.findByPrimaryKey(SGUSERID);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(haysSalGuideUserDataUkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(HaysSalGuideUserDataUk.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SGUSERID");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(haysSalGuideUserDataUkLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(HaysSalGuideUserDataUk.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("SGUSERID");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(haysSalGuideUserDataUkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(HaysSalGuideUserDataUk.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("SGUSERID");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return haysSalGuideUserDataUkLocalService.deleteHaysSalGuideUserDataUk((HaysSalGuideUserDataUk)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return haysSalGuideUserDataUkPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the hays sal guide user data uks.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.hays.service.salaryguide.model.impl.HaysSalGuideUserDataUkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of hays sal guide user data uks
	 * @param end the upper bound of the range of hays sal guide user data uks (not inclusive)
	 * @return the range of hays sal guide user data uks
	 */
	@Override
	public List<HaysSalGuideUserDataUk> getHaysSalGuideUserDataUks(int start,
		int end) {
		return haysSalGuideUserDataUkPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of hays sal guide user data uks.
	 *
	 * @return the number of hays sal guide user data uks
	 */
	@Override
	public int getHaysSalGuideUserDataUksCount() {
		return haysSalGuideUserDataUkPersistence.countAll();
	}

	/**
	 * Updates the hays sal guide user data uk in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param haysSalGuideUserDataUk the hays sal guide user data uk
	 * @return the hays sal guide user data uk that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public HaysSalGuideUserDataUk updateHaysSalGuideUserDataUk(
		HaysSalGuideUserDataUk haysSalGuideUserDataUk) {
		return haysSalGuideUserDataUkPersistence.update(haysSalGuideUserDataUk);
	}

	/**
	 * Returns the hays salary guide local service.
	 *
	 * @return the hays salary guide local service
	 */
	public com.hays.service.salaryguide.service.HaysSalaryGuideLocalService getHaysSalaryGuideLocalService() {
		return haysSalaryGuideLocalService;
	}

	/**
	 * Sets the hays salary guide local service.
	 *
	 * @param haysSalaryGuideLocalService the hays salary guide local service
	 */
	public void setHaysSalaryGuideLocalService(
		com.hays.service.salaryguide.service.HaysSalaryGuideLocalService haysSalaryGuideLocalService) {
		this.haysSalaryGuideLocalService = haysSalaryGuideLocalService;
	}

	/**
	 * Returns the hays salary guide persistence.
	 *
	 * @return the hays salary guide persistence
	 */
	public HaysSalaryGuidePersistence getHaysSalaryGuidePersistence() {
		return haysSalaryGuidePersistence;
	}

	/**
	 * Sets the hays salary guide persistence.
	 *
	 * @param haysSalaryGuidePersistence the hays salary guide persistence
	 */
	public void setHaysSalaryGuidePersistence(
		HaysSalaryGuidePersistence haysSalaryGuidePersistence) {
		this.haysSalaryGuidePersistence = haysSalaryGuidePersistence;
	}

	/**
	 * Returns the hays salary guide finder.
	 *
	 * @return the hays salary guide finder
	 */
	public HaysSalaryGuideFinder getHaysSalaryGuideFinder() {
		return haysSalaryGuideFinder;
	}

	/**
	 * Sets the hays salary guide finder.
	 *
	 * @param haysSalaryGuideFinder the hays salary guide finder
	 */
	public void setHaysSalaryGuideFinder(
		HaysSalaryGuideFinder haysSalaryGuideFinder) {
		this.haysSalaryGuideFinder = haysSalaryGuideFinder;
	}

	/**
	 * Returns the hays sal guide user data uk local service.
	 *
	 * @return the hays sal guide user data uk local service
	 */
	public HaysSalGuideUserDataUkLocalService getHaysSalGuideUserDataUkLocalService() {
		return haysSalGuideUserDataUkLocalService;
	}

	/**
	 * Sets the hays sal guide user data uk local service.
	 *
	 * @param haysSalGuideUserDataUkLocalService the hays sal guide user data uk local service
	 */
	public void setHaysSalGuideUserDataUkLocalService(
		HaysSalGuideUserDataUkLocalService haysSalGuideUserDataUkLocalService) {
		this.haysSalGuideUserDataUkLocalService = haysSalGuideUserDataUkLocalService;
	}

	/**
	 * Returns the hays sal guide user data uk persistence.
	 *
	 * @return the hays sal guide user data uk persistence
	 */
	public HaysSalGuideUserDataUkPersistence getHaysSalGuideUserDataUkPersistence() {
		return haysSalGuideUserDataUkPersistence;
	}

	/**
	 * Sets the hays sal guide user data uk persistence.
	 *
	 * @param haysSalGuideUserDataUkPersistence the hays sal guide user data uk persistence
	 */
	public void setHaysSalGuideUserDataUkPersistence(
		HaysSalGuideUserDataUkPersistence haysSalGuideUserDataUkPersistence) {
		this.haysSalGuideUserDataUkPersistence = haysSalGuideUserDataUkPersistence;
	}

	/**
	 * Returns the hays sg user data local service.
	 *
	 * @return the hays sg user data local service
	 */
	public com.hays.service.salaryguide.service.HaysSGUserDataLocalService getHaysSGUserDataLocalService() {
		return haysSGUserDataLocalService;
	}

	/**
	 * Sets the hays sg user data local service.
	 *
	 * @param haysSGUserDataLocalService the hays sg user data local service
	 */
	public void setHaysSGUserDataLocalService(
		com.hays.service.salaryguide.service.HaysSGUserDataLocalService haysSGUserDataLocalService) {
		this.haysSGUserDataLocalService = haysSGUserDataLocalService;
	}

	/**
	 * Returns the hays sg user data persistence.
	 *
	 * @return the hays sg user data persistence
	 */
	public HaysSGUserDataPersistence getHaysSGUserDataPersistence() {
		return haysSGUserDataPersistence;
	}

	/**
	 * Sets the hays sg user data persistence.
	 *
	 * @param haysSGUserDataPersistence the hays sg user data persistence
	 */
	public void setHaysSGUserDataPersistence(
		HaysSGUserDataPersistence haysSGUserDataPersistence) {
		this.haysSGUserDataPersistence = haysSGUserDataPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.hays.service.salaryguide.model.HaysSalGuideUserDataUk",
			haysSalGuideUserDataUkLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.hays.service.salaryguide.model.HaysSalGuideUserDataUk");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HaysSalGuideUserDataUkLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return HaysSalGuideUserDataUk.class;
	}

	protected String getModelClassName() {
		return HaysSalGuideUserDataUk.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = haysSalGuideUserDataUkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.hays.service.salaryguide.service.HaysSalaryGuideLocalService.class)
	protected com.hays.service.salaryguide.service.HaysSalaryGuideLocalService haysSalaryGuideLocalService;
	@BeanReference(type = HaysSalaryGuidePersistence.class)
	protected HaysSalaryGuidePersistence haysSalaryGuidePersistence;
	@BeanReference(type = HaysSalaryGuideFinder.class)
	protected HaysSalaryGuideFinder haysSalaryGuideFinder;
	@BeanReference(type = HaysSalGuideUserDataUkLocalService.class)
	protected HaysSalGuideUserDataUkLocalService haysSalGuideUserDataUkLocalService;
	@BeanReference(type = HaysSalGuideUserDataUkPersistence.class)
	protected HaysSalGuideUserDataUkPersistence haysSalGuideUserDataUkPersistence;
	@BeanReference(type = com.hays.service.salaryguide.service.HaysSGUserDataLocalService.class)
	protected com.hays.service.salaryguide.service.HaysSGUserDataLocalService haysSGUserDataLocalService;
	@BeanReference(type = HaysSGUserDataPersistence.class)
	protected HaysSGUserDataPersistence haysSGUserDataPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}