/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hays.service.salaryguide.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the HaysSalaryGuide service. Represents a row in the &quot;webcmscustom.HAYS_SALARY_GUIDE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hays.service.salaryguide.model.impl.HaysSalaryGuideModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hays.service.salaryguide.model.impl.HaysSalaryGuideImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HaysSalaryGuide
 * @see com.hays.service.salaryguide.model.impl.HaysSalaryGuideImpl
 * @see com.hays.service.salaryguide.model.impl.HaysSalaryGuideModelImpl
 * @generated
 */
@ProviderType
public interface HaysSalaryGuideModel extends BaseModel<HaysSalaryGuide> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hays salary guide model instance should use the {@link HaysSalaryGuide} interface instead.
	 */

	/**
	 * Returns the primary key of this hays salary guide.
	 *
	 * @return the primary key of this hays salary guide
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this hays salary guide.
	 *
	 * @param primaryKey the primary key of this hays salary guide
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the industry of this hays salary guide.
	 *
	 * @return the industry of this hays salary guide
	 */
	@AutoEscape
	public String getINDUSTRY();

	/**
	 * Sets the industry of this hays salary guide.
	 *
	 * @param INDUSTRY the industry of this hays salary guide
	 */
	public void setINDUSTRY(String INDUSTRY);

	/**
	 * Returns the locationname of this hays salary guide.
	 *
	 * @return the locationname of this hays salary guide
	 */
	@AutoEscape
	public String getLOCATIONNAME();

	/**
	 * Sets the locationname of this hays salary guide.
	 *
	 * @param LOCATIONNAME the locationname of this hays salary guide
	 */
	public void setLOCATIONNAME(String LOCATIONNAME);

	/**
	 * Returns the sector of this hays salary guide.
	 *
	 * @return the sector of this hays salary guide
	 */
	@AutoEscape
	public String getSECTOR();

	/**
	 * Sets the sector of this hays salary guide.
	 *
	 * @param SECTOR the sector of this hays salary guide
	 */
	public void setSECTOR(String SECTOR);

	/**
	 * Returns the positiontype of this hays salary guide.
	 *
	 * @return the positiontype of this hays salary guide
	 */
	@AutoEscape
	public String getPOSITIONTYPE();

	/**
	 * Sets the positiontype of this hays salary guide.
	 *
	 * @param POSITIONTYPE the positiontype of this hays salary guide
	 */
	public void setPOSITIONTYPE(String POSITIONTYPE);

	/**
	 * Returns the area of this hays salary guide.
	 *
	 * @return the area of this hays salary guide
	 */
	@AutoEscape
	public String getAREA();

	/**
	 * Sets the area of this hays salary guide.
	 *
	 * @param AREA the area of this hays salary guide
	 */
	public void setAREA(String AREA);

	/**
	 * Returns the company of this hays salary guide.
	 *
	 * @return the company of this hays salary guide
	 */
	@AutoEscape
	public String getCOMPANY();

	/**
	 * Sets the company of this hays salary guide.
	 *
	 * @param COMPANY the company of this hays salary guide
	 */
	public void setCOMPANY(String COMPANY);

	/**
	 * Returns the positionname of this hays salary guide.
	 *
	 * @return the positionname of this hays salary guide
	 */
	@AutoEscape
	public String getPOSITIONNAME();

	/**
	 * Sets the positionname of this hays salary guide.
	 *
	 * @param POSITIONNAME the positionname of this hays salary guide
	 */
	public void setPOSITIONNAME(String POSITIONNAME);

	/**
	 * Returns the salaryrange of this hays salary guide.
	 *
	 * @return the salaryrange of this hays salary guide
	 */
	@AutoEscape
	public String getSALARYRANGE();

	/**
	 * Sets the salaryrange of this hays salary guide.
	 *
	 * @param SALARYRANGE the salaryrange of this hays salary guide
	 */
	public void setSALARYRANGE(String SALARYRANGE);

	/**
	 * Returns the salarytypical of this hays salary guide.
	 *
	 * @return the salarytypical of this hays salary guide
	 */
	@AutoEscape
	public String getSALARYTYPICAL();

	/**
	 * Sets the salarytypical of this hays salary guide.
	 *
	 * @param SALARYTYPICAL the salarytypical of this hays salary guide
	 */
	public void setSALARYTYPICAL(String SALARYTYPICAL);

	/**
	 * Returns the note of this hays salary guide.
	 *
	 * @return the note of this hays salary guide
	 */
	@AutoEscape
	public String getNOTE();

	/**
	 * Sets the note of this hays salary guide.
	 *
	 * @param NOTE the note of this hays salary guide
	 */
	public void setNOTE(String NOTE);

	/**
	 * Returns the sitelocale of this hays salary guide.
	 *
	 * @return the sitelocale of this hays salary guide
	 */
	@AutoEscape
	public String getSITELOCALE();

	/**
	 * Sets the sitelocale of this hays salary guide.
	 *
	 * @param SITELOCALE the sitelocale of this hays salary guide
	 */
	public void setSITELOCALE(String SITELOCALE);

	/**
	 * Returns the sgddocname of this hays salary guide.
	 *
	 * @return the sgddocname of this hays salary guide
	 */
	@AutoEscape
	public String getSGDDOCNAME();

	/**
	 * Sets the sgddocname of this hays salary guide.
	 *
	 * @param SGDDOCNAME the sgddocname of this hays salary guide
	 */
	public void setSGDDOCNAME(String SGDDOCNAME);

	/**
	 * Returns the sgid of this hays salary guide.
	 *
	 * @return the sgid of this hays salary guide
	 */
	@AutoEscape
	public String getSGID();

	/**
	 * Sets the sgid of this hays salary guide.
	 *
	 * @param SGID the sgid of this hays salary guide
	 */
	public void setSGID(String SGID);

	/**
	 * Returns the salarytype of this hays salary guide.
	 *
	 * @return the salarytype of this hays salary guide
	 */
	@AutoEscape
	public String getSALARYTYPE();

	/**
	 * Sets the salarytype of this hays salary guide.
	 *
	 * @param SALARYTYPE the salarytype of this hays salary guide
	 */
	public void setSALARYTYPE(String SALARYTYPE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HaysSalaryGuide haysSalaryGuide);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HaysSalaryGuide> toCacheModel();

	@Override
	public HaysSalaryGuide toEscapedModel();

	@Override
	public HaysSalaryGuide toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}