/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hays.service.salaryguide.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HaysSGUserData service. Represents a row in the &quot;webcmscustom.HAYSSGUSERDATA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hays.service.salaryguide.model.impl.HaysSGUserDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hays.service.salaryguide.model.impl.HaysSGUserDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HaysSGUserData
 * @see com.hays.service.salaryguide.model.impl.HaysSGUserDataImpl
 * @see com.hays.service.salaryguide.model.impl.HaysSGUserDataModelImpl
 * @generated
 */
@ProviderType
public interface HaysSGUserDataModel extends BaseModel<HaysSGUserData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hays sg user data model instance should use the {@link HaysSGUserData} interface instead.
	 */

	/**
	 * Returns the primary key of this hays sg user data.
	 *
	 * @return the primary key of this hays sg user data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hays sg user data.
	 *
	 * @param primaryKey the primary key of this hays sg user data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the sguserid of this hays sg user data.
	 *
	 * @return the sguserid of this hays sg user data
	 */
	public long getSGUSERID();

	/**
	 * Sets the sguserid of this hays sg user data.
	 *
	 * @param SGUSERID the sguserid of this hays sg user data
	 */
	public void setSGUSERID(long SGUSERID);

	/**
	 * Returns the sgusername of this hays sg user data.
	 *
	 * @return the sgusername of this hays sg user data
	 */
	@AutoEscape
	public String getSGUSERNAME();

	/**
	 * Sets the sgusername of this hays sg user data.
	 *
	 * @param SGUSERNAME the sgusername of this hays sg user data
	 */
	public void setSGUSERNAME(String SGUSERNAME);

	/**
	 * Returns the sgjobtitle of this hays sg user data.
	 *
	 * @return the sgjobtitle of this hays sg user data
	 */
	@AutoEscape
	public String getSGJOBTITLE();

	/**
	 * Sets the sgjobtitle of this hays sg user data.
	 *
	 * @param SGJOBTITLE the sgjobtitle of this hays sg user data
	 */
	public void setSGJOBTITLE(String SGJOBTITLE);

	/**
	 * Returns the sgorganization of this hays sg user data.
	 *
	 * @return the sgorganization of this hays sg user data
	 */
	@AutoEscape
	public String getSGORGANIZATION();

	/**
	 * Sets the sgorganization of this hays sg user data.
	 *
	 * @param SGORGANIZATION the sgorganization of this hays sg user data
	 */
	public void setSGORGANIZATION(String SGORGANIZATION);

	/**
	 * Returns the sglocation of this hays sg user data.
	 *
	 * @return the sglocation of this hays sg user data
	 */
	@AutoEscape
	public String getSGLOCATION();

	/**
	 * Sets the sglocation of this hays sg user data.
	 *
	 * @param SGLOCATION the sglocation of this hays sg user data
	 */
	public void setSGLOCATION(String SGLOCATION);

	/**
	 * Returns the sgemailaddress of this hays sg user data.
	 *
	 * @return the sgemailaddress of this hays sg user data
	 */
	@AutoEscape
	public String getSGEMAILADDRESS();

	/**
	 * Sets the sgemailaddress of this hays sg user data.
	 *
	 * @param SGEMAILADDRESS the sgemailaddress of this hays sg user data
	 */
	public void setSGEMAILADDRESS(String SGEMAILADDRESS);

	/**
	 * Returns the fromlocale of this hays sg user data.
	 *
	 * @return the fromlocale of this hays sg user data
	 */
	@AutoEscape
	public String getFROMLOCALE();

	/**
	 * Sets the fromlocale of this hays sg user data.
	 *
	 * @param FROMLOCALE the fromlocale of this hays sg user data
	 */
	public void setFROMLOCALE(String FROMLOCALE);

	/**
	 * Returns the createtimestamp of this hays sg user data.
	 *
	 * @return the createtimestamp of this hays sg user data
	 */
	public Date getCREATETIMESTAMP();

	/**
	 * Sets the createtimestamp of this hays sg user data.
	 *
	 * @param CREATETIMESTAMP the createtimestamp of this hays sg user data
	 */
	public void setCREATETIMESTAMP(Date CREATETIMESTAMP);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HaysSGUserData haysSGUserData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HaysSGUserData> toCacheModel();

	@Override
	public HaysSGUserData toEscapedModel();

	@Override
	public HaysSGUserData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}