/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hays.service.salaryguide.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.hays.service.salaryguide.model.HaysSalaryGuide;
import com.hays.service.salaryguide.model.HaysSalaryGuideModel;
import com.hays.service.salaryguide.model.HaysSalaryGuideSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the HaysSalaryGuide service. Represents a row in the &quot;webcmscustom.HAYS_SALARY_GUIDE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link HaysSalaryGuideModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HaysSalaryGuideImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HaysSalaryGuideImpl
 * @see HaysSalaryGuide
 * @see HaysSalaryGuideModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class HaysSalaryGuideModelImpl extends BaseModelImpl<HaysSalaryGuide>
	implements HaysSalaryGuideModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hays salary guide model instance should use the {@link HaysSalaryGuide} interface instead.
	 */
	public static final String TABLE_NAME = "webcmscustom.HAYS_SALARY_GUIDE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "INDUSTRY", Types.VARCHAR },
			{ "LOCATIONNAME", Types.VARCHAR },
			{ "SECTOR", Types.VARCHAR },
			{ "POSITIONTYPE", Types.VARCHAR },
			{ "AREA", Types.VARCHAR },
			{ "COMPANY", Types.VARCHAR },
			{ "POSITIONNAME", Types.VARCHAR },
			{ "SALARYRANGE", Types.VARCHAR },
			{ "SALARYTYPICAL", Types.VARCHAR },
			{ "NOTE", Types.VARCHAR },
			{ "SITELOCALE", Types.VARCHAR },
			{ "SGDDOCNAME", Types.VARCHAR },
			{ "SGID", Types.VARCHAR },
			{ "SALARYTYPE", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("INDUSTRY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("LOCATIONNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SECTOR", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("POSITIONTYPE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("AREA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COMPANY", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("POSITIONNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SALARYRANGE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SALARYTYPICAL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NOTE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SITELOCALE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SGDDOCNAME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SGID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("SALARYTYPE", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table webcmscustom.HAYS_SALARY_GUIDE (INDUSTRY VARCHAR(75) null,LOCATIONNAME VARCHAR(75) null,SECTOR VARCHAR(75) null,POSITIONTYPE VARCHAR(75) null,AREA VARCHAR(75) null,COMPANY VARCHAR(75) null,POSITIONNAME VARCHAR(75) null,SALARYRANGE VARCHAR(75) null,SALARYTYPICAL VARCHAR(75) null,NOTE VARCHAR(75) null,SITELOCALE VARCHAR(75) null,SGDDOCNAME VARCHAR(75) null,SGID VARCHAR(75) not null primary key,SALARYTYPE VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table webcmscustom.HAYS_SALARY_GUIDE";
	public static final String ORDER_BY_JPQL = " ORDER BY haysSalaryGuide.SGID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY webcmscustom.HAYS_SALARY_GUIDE.SGID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.hays.service.salaryguide.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.hays.service.salaryguide.model.HaysSalaryGuide"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.hays.service.salaryguide.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.hays.service.salaryguide.model.HaysSalaryGuide"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.hays.service.salaryguide.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.hays.service.salaryguide.model.HaysSalaryGuide"),
			true);
	public static final long INDUSTRY_COLUMN_BITMASK = 1L;
	public static final long SITELOCALE_COLUMN_BITMASK = 2L;
	public static final long SGID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static HaysSalaryGuide toModel(HaysSalaryGuideSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		HaysSalaryGuide model = new HaysSalaryGuideImpl();

		model.setINDUSTRY(soapModel.getINDUSTRY());
		model.setLOCATIONNAME(soapModel.getLOCATIONNAME());
		model.setSECTOR(soapModel.getSECTOR());
		model.setPOSITIONTYPE(soapModel.getPOSITIONTYPE());
		model.setAREA(soapModel.getAREA());
		model.setCOMPANY(soapModel.getCOMPANY());
		model.setPOSITIONNAME(soapModel.getPOSITIONNAME());
		model.setSALARYRANGE(soapModel.getSALARYRANGE());
		model.setSALARYTYPICAL(soapModel.getSALARYTYPICAL());
		model.setNOTE(soapModel.getNOTE());
		model.setSITELOCALE(soapModel.getSITELOCALE());
		model.setSGDDOCNAME(soapModel.getSGDDOCNAME());
		model.setSGID(soapModel.getSGID());
		model.setSALARYTYPE(soapModel.getSALARYTYPE());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<HaysSalaryGuide> toModels(
		HaysSalaryGuideSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<HaysSalaryGuide> models = new ArrayList<HaysSalaryGuide>(soapModels.length);

		for (HaysSalaryGuideSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.hays.service.salaryguide.service.util.ServiceProps.get(
				"lock.expiration.time.com.hays.service.salaryguide.model.HaysSalaryGuide"));

	public HaysSalaryGuideModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _SGID;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setSGID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _SGID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return HaysSalaryGuide.class;
	}

	@Override
	public String getModelClassName() {
		return HaysSalaryGuide.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("INDUSTRY", getINDUSTRY());
		attributes.put("LOCATIONNAME", getLOCATIONNAME());
		attributes.put("SECTOR", getSECTOR());
		attributes.put("POSITIONTYPE", getPOSITIONTYPE());
		attributes.put("AREA", getAREA());
		attributes.put("COMPANY", getCOMPANY());
		attributes.put("POSITIONNAME", getPOSITIONNAME());
		attributes.put("SALARYRANGE", getSALARYRANGE());
		attributes.put("SALARYTYPICAL", getSALARYTYPICAL());
		attributes.put("NOTE", getNOTE());
		attributes.put("SITELOCALE", getSITELOCALE());
		attributes.put("SGDDOCNAME", getSGDDOCNAME());
		attributes.put("SGID", getSGID());
		attributes.put("SALARYTYPE", getSALARYTYPE());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String INDUSTRY = (String)attributes.get("INDUSTRY");

		if (INDUSTRY != null) {
			setINDUSTRY(INDUSTRY);
		}

		String LOCATIONNAME = (String)attributes.get("LOCATIONNAME");

		if (LOCATIONNAME != null) {
			setLOCATIONNAME(LOCATIONNAME);
		}

		String SECTOR = (String)attributes.get("SECTOR");

		if (SECTOR != null) {
			setSECTOR(SECTOR);
		}

		String POSITIONTYPE = (String)attributes.get("POSITIONTYPE");

		if (POSITIONTYPE != null) {
			setPOSITIONTYPE(POSITIONTYPE);
		}

		String AREA = (String)attributes.get("AREA");

		if (AREA != null) {
			setAREA(AREA);
		}

		String COMPANY = (String)attributes.get("COMPANY");

		if (COMPANY != null) {
			setCOMPANY(COMPANY);
		}

		String POSITIONNAME = (String)attributes.get("POSITIONNAME");

		if (POSITIONNAME != null) {
			setPOSITIONNAME(POSITIONNAME);
		}

		String SALARYRANGE = (String)attributes.get("SALARYRANGE");

		if (SALARYRANGE != null) {
			setSALARYRANGE(SALARYRANGE);
		}

		String SALARYTYPICAL = (String)attributes.get("SALARYTYPICAL");

		if (SALARYTYPICAL != null) {
			setSALARYTYPICAL(SALARYTYPICAL);
		}

		String NOTE = (String)attributes.get("NOTE");

		if (NOTE != null) {
			setNOTE(NOTE);
		}

		String SITELOCALE = (String)attributes.get("SITELOCALE");

		if (SITELOCALE != null) {
			setSITELOCALE(SITELOCALE);
		}

		String SGDDOCNAME = (String)attributes.get("SGDDOCNAME");

		if (SGDDOCNAME != null) {
			setSGDDOCNAME(SGDDOCNAME);
		}

		String SGID = (String)attributes.get("SGID");

		if (SGID != null) {
			setSGID(SGID);
		}

		String SALARYTYPE = (String)attributes.get("SALARYTYPE");

		if (SALARYTYPE != null) {
			setSALARYTYPE(SALARYTYPE);
		}
	}

	@JSON
	@Override
	public String getINDUSTRY() {
		if (_INDUSTRY == null) {
			return StringPool.BLANK;
		}
		else {
			return _INDUSTRY;
		}
	}

	@Override
	public void setINDUSTRY(String INDUSTRY) {
		_columnBitmask |= INDUSTRY_COLUMN_BITMASK;

		if (_originalINDUSTRY == null) {
			_originalINDUSTRY = _INDUSTRY;
		}

		_INDUSTRY = INDUSTRY;
	}

	public String getOriginalINDUSTRY() {
		return GetterUtil.getString(_originalINDUSTRY);
	}

	@JSON
	@Override
	public String getLOCATIONNAME() {
		if (_LOCATIONNAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _LOCATIONNAME;
		}
	}

	@Override
	public void setLOCATIONNAME(String LOCATIONNAME) {
		_LOCATIONNAME = LOCATIONNAME;
	}

	@JSON
	@Override
	public String getSECTOR() {
		if (_SECTOR == null) {
			return StringPool.BLANK;
		}
		else {
			return _SECTOR;
		}
	}

	@Override
	public void setSECTOR(String SECTOR) {
		_SECTOR = SECTOR;
	}

	@JSON
	@Override
	public String getPOSITIONTYPE() {
		if (_POSITIONTYPE == null) {
			return StringPool.BLANK;
		}
		else {
			return _POSITIONTYPE;
		}
	}

	@Override
	public void setPOSITIONTYPE(String POSITIONTYPE) {
		_POSITIONTYPE = POSITIONTYPE;
	}

	@JSON
	@Override
	public String getAREA() {
		if (_AREA == null) {
			return StringPool.BLANK;
		}
		else {
			return _AREA;
		}
	}

	@Override
	public void setAREA(String AREA) {
		_AREA = AREA;
	}

	@JSON
	@Override
	public String getCOMPANY() {
		if (_COMPANY == null) {
			return StringPool.BLANK;
		}
		else {
			return _COMPANY;
		}
	}

	@Override
	public void setCOMPANY(String COMPANY) {
		_COMPANY = COMPANY;
	}

	@JSON
	@Override
	public String getPOSITIONNAME() {
		if (_POSITIONNAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _POSITIONNAME;
		}
	}

	@Override
	public void setPOSITIONNAME(String POSITIONNAME) {
		_POSITIONNAME = POSITIONNAME;
	}

	@JSON
	@Override
	public String getSALARYRANGE() {
		if (_SALARYRANGE == null) {
			return StringPool.BLANK;
		}
		else {
			return _SALARYRANGE;
		}
	}

	@Override
	public void setSALARYRANGE(String SALARYRANGE) {
		_SALARYRANGE = SALARYRANGE;
	}

	@JSON
	@Override
	public String getSALARYTYPICAL() {
		if (_SALARYTYPICAL == null) {
			return StringPool.BLANK;
		}
		else {
			return _SALARYTYPICAL;
		}
	}

	@Override
	public void setSALARYTYPICAL(String SALARYTYPICAL) {
		_SALARYTYPICAL = SALARYTYPICAL;
	}

	@JSON
	@Override
	public String getNOTE() {
		if (_NOTE == null) {
			return StringPool.BLANK;
		}
		else {
			return _NOTE;
		}
	}

	@Override
	public void setNOTE(String NOTE) {
		_NOTE = NOTE;
	}

	@JSON
	@Override
	public String getSITELOCALE() {
		if (_SITELOCALE == null) {
			return StringPool.BLANK;
		}
		else {
			return _SITELOCALE;
		}
	}

	@Override
	public void setSITELOCALE(String SITELOCALE) {
		_columnBitmask |= SITELOCALE_COLUMN_BITMASK;

		if (_originalSITELOCALE == null) {
			_originalSITELOCALE = _SITELOCALE;
		}

		_SITELOCALE = SITELOCALE;
	}

	public String getOriginalSITELOCALE() {
		return GetterUtil.getString(_originalSITELOCALE);
	}

	@JSON
	@Override
	public String getSGDDOCNAME() {
		if (_SGDDOCNAME == null) {
			return StringPool.BLANK;
		}
		else {
			return _SGDDOCNAME;
		}
	}

	@Override
	public void setSGDDOCNAME(String SGDDOCNAME) {
		_SGDDOCNAME = SGDDOCNAME;
	}

	@JSON
	@Override
	public String getSGID() {
		if (_SGID == null) {
			return StringPool.BLANK;
		}
		else {
			return _SGID;
		}
	}

	@Override
	public void setSGID(String SGID) {
		_SGID = SGID;
	}

	@JSON
	@Override
	public String getSALARYTYPE() {
		if (_SALARYTYPE == null) {
			return StringPool.BLANK;
		}
		else {
			return _SALARYTYPE;
		}
	}

	@Override
	public void setSALARYTYPE(String SALARYTYPE) {
		_SALARYTYPE = SALARYTYPE;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public HaysSalaryGuide toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (HaysSalaryGuide)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HaysSalaryGuideImpl haysSalaryGuideImpl = new HaysSalaryGuideImpl();

		haysSalaryGuideImpl.setINDUSTRY(getINDUSTRY());
		haysSalaryGuideImpl.setLOCATIONNAME(getLOCATIONNAME());
		haysSalaryGuideImpl.setSECTOR(getSECTOR());
		haysSalaryGuideImpl.setPOSITIONTYPE(getPOSITIONTYPE());
		haysSalaryGuideImpl.setAREA(getAREA());
		haysSalaryGuideImpl.setCOMPANY(getCOMPANY());
		haysSalaryGuideImpl.setPOSITIONNAME(getPOSITIONNAME());
		haysSalaryGuideImpl.setSALARYRANGE(getSALARYRANGE());
		haysSalaryGuideImpl.setSALARYTYPICAL(getSALARYTYPICAL());
		haysSalaryGuideImpl.setNOTE(getNOTE());
		haysSalaryGuideImpl.setSITELOCALE(getSITELOCALE());
		haysSalaryGuideImpl.setSGDDOCNAME(getSGDDOCNAME());
		haysSalaryGuideImpl.setSGID(getSGID());
		haysSalaryGuideImpl.setSALARYTYPE(getSALARYTYPE());

		haysSalaryGuideImpl.resetOriginalValues();

		return haysSalaryGuideImpl;
	}

	@Override
	public int compareTo(HaysSalaryGuide haysSalaryGuide) {
		String primaryKey = haysSalaryGuide.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof HaysSalaryGuide)) {
			return false;
		}

		HaysSalaryGuide haysSalaryGuide = (HaysSalaryGuide)obj;

		String primaryKey = haysSalaryGuide.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		HaysSalaryGuideModelImpl haysSalaryGuideModelImpl = this;

		haysSalaryGuideModelImpl._originalINDUSTRY = haysSalaryGuideModelImpl._INDUSTRY;

		haysSalaryGuideModelImpl._originalSITELOCALE = haysSalaryGuideModelImpl._SITELOCALE;

		haysSalaryGuideModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<HaysSalaryGuide> toCacheModel() {
		HaysSalaryGuideCacheModel haysSalaryGuideCacheModel = new HaysSalaryGuideCacheModel();

		haysSalaryGuideCacheModel.INDUSTRY = getINDUSTRY();

		String INDUSTRY = haysSalaryGuideCacheModel.INDUSTRY;

		if ((INDUSTRY != null) && (INDUSTRY.length() == 0)) {
			haysSalaryGuideCacheModel.INDUSTRY = null;
		}

		haysSalaryGuideCacheModel.LOCATIONNAME = getLOCATIONNAME();

		String LOCATIONNAME = haysSalaryGuideCacheModel.LOCATIONNAME;

		if ((LOCATIONNAME != null) && (LOCATIONNAME.length() == 0)) {
			haysSalaryGuideCacheModel.LOCATIONNAME = null;
		}

		haysSalaryGuideCacheModel.SECTOR = getSECTOR();

		String SECTOR = haysSalaryGuideCacheModel.SECTOR;

		if ((SECTOR != null) && (SECTOR.length() == 0)) {
			haysSalaryGuideCacheModel.SECTOR = null;
		}

		haysSalaryGuideCacheModel.POSITIONTYPE = getPOSITIONTYPE();

		String POSITIONTYPE = haysSalaryGuideCacheModel.POSITIONTYPE;

		if ((POSITIONTYPE != null) && (POSITIONTYPE.length() == 0)) {
			haysSalaryGuideCacheModel.POSITIONTYPE = null;
		}

		haysSalaryGuideCacheModel.AREA = getAREA();

		String AREA = haysSalaryGuideCacheModel.AREA;

		if ((AREA != null) && (AREA.length() == 0)) {
			haysSalaryGuideCacheModel.AREA = null;
		}

		haysSalaryGuideCacheModel.COMPANY = getCOMPANY();

		String COMPANY = haysSalaryGuideCacheModel.COMPANY;

		if ((COMPANY != null) && (COMPANY.length() == 0)) {
			haysSalaryGuideCacheModel.COMPANY = null;
		}

		haysSalaryGuideCacheModel.POSITIONNAME = getPOSITIONNAME();

		String POSITIONNAME = haysSalaryGuideCacheModel.POSITIONNAME;

		if ((POSITIONNAME != null) && (POSITIONNAME.length() == 0)) {
			haysSalaryGuideCacheModel.POSITIONNAME = null;
		}

		haysSalaryGuideCacheModel.SALARYRANGE = getSALARYRANGE();

		String SALARYRANGE = haysSalaryGuideCacheModel.SALARYRANGE;

		if ((SALARYRANGE != null) && (SALARYRANGE.length() == 0)) {
			haysSalaryGuideCacheModel.SALARYRANGE = null;
		}

		haysSalaryGuideCacheModel.SALARYTYPICAL = getSALARYTYPICAL();

		String SALARYTYPICAL = haysSalaryGuideCacheModel.SALARYTYPICAL;

		if ((SALARYTYPICAL != null) && (SALARYTYPICAL.length() == 0)) {
			haysSalaryGuideCacheModel.SALARYTYPICAL = null;
		}

		haysSalaryGuideCacheModel.NOTE = getNOTE();

		String NOTE = haysSalaryGuideCacheModel.NOTE;

		if ((NOTE != null) && (NOTE.length() == 0)) {
			haysSalaryGuideCacheModel.NOTE = null;
		}

		haysSalaryGuideCacheModel.SITELOCALE = getSITELOCALE();

		String SITELOCALE = haysSalaryGuideCacheModel.SITELOCALE;

		if ((SITELOCALE != null) && (SITELOCALE.length() == 0)) {
			haysSalaryGuideCacheModel.SITELOCALE = null;
		}

		haysSalaryGuideCacheModel.SGDDOCNAME = getSGDDOCNAME();

		String SGDDOCNAME = haysSalaryGuideCacheModel.SGDDOCNAME;

		if ((SGDDOCNAME != null) && (SGDDOCNAME.length() == 0)) {
			haysSalaryGuideCacheModel.SGDDOCNAME = null;
		}

		haysSalaryGuideCacheModel.SGID = getSGID();

		String SGID = haysSalaryGuideCacheModel.SGID;

		if ((SGID != null) && (SGID.length() == 0)) {
			haysSalaryGuideCacheModel.SGID = null;
		}

		haysSalaryGuideCacheModel.SALARYTYPE = getSALARYTYPE();

		String SALARYTYPE = haysSalaryGuideCacheModel.SALARYTYPE;

		if ((SALARYTYPE != null) && (SALARYTYPE.length() == 0)) {
			haysSalaryGuideCacheModel.SALARYTYPE = null;
		}

		return haysSalaryGuideCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{INDUSTRY=");
		sb.append(getINDUSTRY());
		sb.append(", LOCATIONNAME=");
		sb.append(getLOCATIONNAME());
		sb.append(", SECTOR=");
		sb.append(getSECTOR());
		sb.append(", POSITIONTYPE=");
		sb.append(getPOSITIONTYPE());
		sb.append(", AREA=");
		sb.append(getAREA());
		sb.append(", COMPANY=");
		sb.append(getCOMPANY());
		sb.append(", POSITIONNAME=");
		sb.append(getPOSITIONNAME());
		sb.append(", SALARYRANGE=");
		sb.append(getSALARYRANGE());
		sb.append(", SALARYTYPICAL=");
		sb.append(getSALARYTYPICAL());
		sb.append(", NOTE=");
		sb.append(getNOTE());
		sb.append(", SITELOCALE=");
		sb.append(getSITELOCALE());
		sb.append(", SGDDOCNAME=");
		sb.append(getSGDDOCNAME());
		sb.append(", SGID=");
		sb.append(getSGID());
		sb.append(", SALARYTYPE=");
		sb.append(getSALARYTYPE());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.hays.service.salaryguide.model.HaysSalaryGuide");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>INDUSTRY</column-name><column-value><![CDATA[");
		sb.append(getINDUSTRY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>LOCATIONNAME</column-name><column-value><![CDATA[");
		sb.append(getLOCATIONNAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SECTOR</column-name><column-value><![CDATA[");
		sb.append(getSECTOR());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POSITIONTYPE</column-name><column-value><![CDATA[");
		sb.append(getPOSITIONTYPE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>AREA</column-name><column-value><![CDATA[");
		sb.append(getAREA());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>COMPANY</column-name><column-value><![CDATA[");
		sb.append(getCOMPANY());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>POSITIONNAME</column-name><column-value><![CDATA[");
		sb.append(getPOSITIONNAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SALARYRANGE</column-name><column-value><![CDATA[");
		sb.append(getSALARYRANGE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SALARYTYPICAL</column-name><column-value><![CDATA[");
		sb.append(getSALARYTYPICAL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>NOTE</column-name><column-value><![CDATA[");
		sb.append(getNOTE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SITELOCALE</column-name><column-value><![CDATA[");
		sb.append(getSITELOCALE());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SGDDOCNAME</column-name><column-value><![CDATA[");
		sb.append(getSGDDOCNAME());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SGID</column-name><column-value><![CDATA[");
		sb.append(getSGID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>SALARYTYPE</column-name><column-value><![CDATA[");
		sb.append(getSALARYTYPE());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = HaysSalaryGuide.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			HaysSalaryGuide.class
		};
	private String _INDUSTRY;
	private String _originalINDUSTRY;
	private String _LOCATIONNAME;
	private String _SECTOR;
	private String _POSITIONTYPE;
	private String _AREA;
	private String _COMPANY;
	private String _POSITIONNAME;
	private String _SALARYRANGE;
	private String _SALARYTYPICAL;
	private String _NOTE;
	private String _SITELOCALE;
	private String _originalSITELOCALE;
	private String _SGDDOCNAME;
	private String _SGID;
	private String _SALARYTYPE;
	private long _columnBitmask;
	private HaysSalaryGuide _escapedModel;
}