/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hays.search.form.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SreeSoluctions service. Represents a row in the &quot;hays_SreeSoluctions&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hays.search.form.model.impl.SreeSoluctionsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hays.search.form.model.impl.SreeSoluctionsImpl}.
 * </p>
 *
 * @author Sreenivasulu
 * @see SreeSoluctions
 * @see com.hays.search.form.model.impl.SreeSoluctionsImpl
 * @see com.hays.search.form.model.impl.SreeSoluctionsModelImpl
 * @generated
 */
@ProviderType
public interface SreeSoluctionsModel extends BaseModel<SreeSoluctions> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sree soluctions model instance should use the {@link SreeSoluctions} interface instead.
	 */

	/**
	 * Returns the primary key of this sree soluctions.
	 *
	 * @return the primary key of this sree soluctions
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sree soluctions.
	 *
	 * @param primaryKey the primary key of this sree soluctions
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the soluction ID of this sree soluctions.
	 *
	 * @return the soluction ID of this sree soluctions
	 */
	public long getSoluctionId();

	/**
	 * Sets the soluction ID of this sree soluctions.
	 *
	 * @param soluctionId the soluction ID of this sree soluctions
	 */
	public void setSoluctionId(long soluctionId);

	/**
	 * Returns the branch ID of this sree soluctions.
	 *
	 * @return the branch ID of this sree soluctions
	 */
	@AutoEscape
	public String getBranchId();

	/**
	 * Sets the branch ID of this sree soluctions.
	 *
	 * @param branchId the branch ID of this sree soluctions
	 */
	public void setBranchId(String branchId);

	/**
	 * Returns the branch address of this sree soluctions.
	 *
	 * @return the branch address of this sree soluctions
	 */
	@AutoEscape
	public String getBranchAddress();

	/**
	 * Sets the branch address of this sree soluctions.
	 *
	 * @param branchAddress the branch address of this sree soluctions
	 */
	public void setBranchAddress(String branchAddress);

	/**
	 * Returns the telephone number of this sree soluctions.
	 *
	 * @return the telephone number of this sree soluctions
	 */
	@AutoEscape
	public String getTelephoneNumber();

	/**
	 * Sets the telephone number of this sree soluctions.
	 *
	 * @param telephoneNumber the telephone number of this sree soluctions
	 */
	public void setTelephoneNumber(String telephoneNumber);

	/**
	 * Returns the office email address of this sree soluctions.
	 *
	 * @return the office email address of this sree soluctions
	 */
	@AutoEscape
	public String getOfficeEmailAddress();

	/**
	 * Sets the office email address of this sree soluctions.
	 *
	 * @param officeEmailAddress the office email address of this sree soluctions
	 */
	public void setOfficeEmailAddress(String officeEmailAddress);

	/**
	 * Returns the employee ID of this sree soluctions.
	 *
	 * @return the employee ID of this sree soluctions
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this sree soluctions.
	 *
	 * @param employeeId the employee ID of this sree soluctions
	 */
	public void setEmployeeId(long employeeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SreeSoluctions sreeSoluctions);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SreeSoluctions> toCacheModel();

	@Override
	public SreeSoluctions toEscapedModel();

	@Override
	public SreeSoluctions toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}